name: Culinary Guide Shop
favicon: null
layout_spectrum: 0.32018
typography_spectrum: 0.18646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d7174'
    - '#d5b06a'
    - '#ea816a'
    - '#ccccd0'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
